apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
  labels:
    app: secret-demo
    type: volume
spec:
  containers:
    - name: app
      image: nginx:alpine
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
  volumes:
    - name: secret-volume
      secret:
        secretName: db-credentials
        # Permisos restrictivos para archivos sensibles
        defaultMode: 0400
