apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
  labels:
    app: secret-demo
    type: env
spec:
  containers:
    - name: app
      image: nginx:alpine
      # Inyectar variables específicas desde un Secret
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
      # Inyectar todas las claves del Secret como variables de entorno
      envFrom:
        - secretRef:
            name: app-secrets
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
