apiVersion: v1
kind: Service
metadata:
  name: web-v1-only
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
