# Ejemplo: ServiceAccount con Azure AD Workload Identity para AKS
# Este ServiceAccount permite a pods acceder a APIs de Azure
# usando Workload Identity (recomendado) o Azure AD Pod Identity (legacy).
#
# Prerequisitos para Workload Identity (metodo recomendado):
# 1. AKS cluster con OIDC Issuer habilitado
# 2. Workload Identity addon habilitado
# 3. Managed Identity creado en Azure
# 4. Federated credential configurado
#
# Comandos para configurar:
#
# 1. Habilitar OIDC issuer en AKS:
# az aks update -g RESOURCE_GROUP -n CLUSTER_NAME --enable-oidc-issuer
#
# 2. Habilitar workload identity:
# az aks update -g RESOURCE_GROUP -n CLUSTER_NAME --enable-workload-identity
#
# 3. Crear Managed Identity:
# az identity create --name my-app-identity --resource-group RESOURCE_GROUP
#
# 4. Crear federated credential:
# az identity federated-credential create \
#   --name my-app-federated-cred \
#   --identity-name my-app-identity \
#   --resource-group RESOURCE_GROUP \
#   --issuer $(az aks show -g RESOURCE_GROUP -n CLUSTER_NAME --query "oidcIssuerProfile.issuerUrl" -o tsv) \
#   --subject "system:serviceaccount:default:azure-workload-identity-sa" \
#   --audiences "api://AzureADTokenExchange"

apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-workload-identity-sa
  namespace: default
  annotations:
    # Esta anotacion vincula el ServiceAccount de Kubernetes
    # con el Managed Identity de Azure
    azure.workload.identity/client-id: <MANAGED_IDENTITY_CLIENT_ID>
  labels:
    # Este label es requerido para que el webhook inyecte las variables
    azure.workload.identity/use: "true"
---
# Ejemplo de Pod usando el ServiceAccount con Azure Workload Identity
apiVersion: v1
kind: Pod
metadata:
  name: azure-workload-identity-demo
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: azure-workload-identity-sa
  containers:
    - name: app
      image: mcr.microsoft.com/azure-cli:latest
      command: ["sleep", "infinity"]
      # El Azure SDK detectara automaticamente las credenciales
      # via workload identity
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
        requests:
          memory: "128Mi"
          cpu: "100m"
      # Las siguientes variables de entorno son inyectadas automaticamente:
      # AZURE_CLIENT_ID: Client ID del Managed Identity
      # AZURE_TENANT_ID: Tenant ID de Azure AD
      # AZURE_FEDERATED_TOKEN_FILE: Path al token JWT
      # AZURE_AUTHORITY_HOST: URL del authority host
---
# Ejemplo alternativo: Azure AD Pod Identity (legacy, no recomendado para nuevos proyectos)
# Este metodo esta siendo reemplazado por Workload Identity
#
# apiVersion: aadpodidentity.k8s.io/v1
# kind: AzureIdentity
# metadata:
#   name: my-azure-identity
#   namespace: default
# spec:
#   type: 0  # 0 = User Assigned Identity, 1 = Service Principal
#   resourceID: /subscriptions/SUB_ID/resourcegroups/RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/IDENTITY_NAME
#   clientID: <MANAGED_IDENTITY_CLIENT_ID>
# ---
# apiVersion: aadpodidentity.k8s.io/v1
# kind: AzureIdentityBinding
# metadata:
#   name: my-azure-identity-binding
#   namespace: default
# spec:
#   azureIdentity: my-azure-identity
#   selector: my-app
