# Ejemplo: ServiceAccount con IAM Roles for Service Accounts (IRSA) para EKS
# Este ServiceAccount permite a pods acceder a APIs de AWS
# usando IRSA en lugar de credenciales estaticas.
#
# Prerequisitos:
# 1. OIDC Provider configurado en el cluster EKS
# 2. IAM Role creado con trust policy para el OIDC provider
# 3. IAM Policies adjuntadas al role
#
# Comandos para configurar (ejecutar fuera del cluster):
#
# 1. Obtener el OIDC issuer URL:
# aws eks describe-cluster --name CLUSTER_NAME --query "cluster.identity.oidc.issuer" --output text
#
# 2. Crear el IAM Role con trust policy:
# aws iam create-role --role-name my-app-role \
#   --assume-role-policy-document file://trust-policy.json
#
# 3. Adjuntar politicas al role:
# aws iam attach-role-policy --role-name my-app-role \
#   --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-irsa-sa
  namespace: default
  annotations:
    # Esta anotacion vincula el ServiceAccount de Kubernetes
    # con el IAM Role de AWS
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/my-app-role
---
# Ejemplo de Pod usando el ServiceAccount con IRSA
apiVersion: v1
kind: Pod
metadata:
  name: aws-irsa-demo
  namespace: default
spec:
  serviceAccountName: aws-irsa-sa
  containers:
    - name: app
      image: amazon/aws-cli:latest
      command: ["sleep", "infinity"]
      # El AWS SDK detectara automaticamente las credenciales
      # via el web identity token montado por IRSA
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
        requests:
          memory: "128Mi"
          cpu: "100m"
      # Las siguientes variables de entorno son inyectadas automaticamente:
      # AWS_ROLE_ARN: ARN del IAM role
      # AWS_WEB_IDENTITY_TOKEN_FILE: Path al token JWT
---
# Trust Policy de ejemplo para el IAM Role (trust-policy.json)
# Este archivo NO es un recurso de Kubernetes, sino un archivo JSON
# que se usa al crear el IAM Role en AWS
#
# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Principal": {
#         "Federated": "arn:aws:iam::123456789012:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/EXAMPLED539D4633E53DE1B71EXAMPLE"
#       },
#       "Action": "sts:AssumeRoleWithWebIdentity",
#       "Condition": {
#         "StringEquals": {
#           "oidc.eks.us-east-1.amazonaws.com/id/EXAMPLED539D4633E53DE1B71EXAMPLE:sub": "system:serviceaccount:default:aws-irsa-sa",
#           "oidc.eks.us-east-1.amazonaws.com/id/EXAMPLED539D4633E53DE1B71EXAMPLE:aud": "sts.amazonaws.com"
#         }
#       }
#     }
#   ]
# }
