# Ejemplo: ServiceAccount con Workload Identity para GKE
# Este ServiceAccount permite a pods acceder a APIs de Google Cloud
# usando Workload Identity en lugar de credenciales estaticas.
#
# Prerequisitos:
# 1. Workload Identity habilitado en el cluster GKE
# 2. Service Account de GCP creado con los permisos necesarios
# 3. Binding entre el Service Account de Kubernetes y el de GCP
#
# Comandos para configurar (ejecutar fuera del cluster):
# gcloud iam service-accounts create my-app-sa --display-name="My App Service Account"
# gcloud projects add-iam-policy-binding PROJECT_ID \
#   --member="serviceAccount:my-app-sa@PROJECT_ID.iam.gserviceaccount.com" \
#   --role="roles/storage.objectViewer"
# gcloud iam service-accounts add-iam-policy-binding my-app-sa@PROJECT_ID.iam.gserviceaccount.com \
#   --role="roles/iam.workloadIdentityUser" \
#   --member="serviceAccount:PROJECT_ID.svc.id.goog[NAMESPACE/KSA_NAME]"

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-workload-identity-sa
  namespace: default
  annotations:
    # Esta anotacion vincula el ServiceAccount de Kubernetes
    # con el Service Account de Google Cloud Platform
    iam.gke.io/gcp-service-account: my-app-sa@PROJECT_ID.iam.gserviceaccount.com
---
# Ejemplo de Pod usando el ServiceAccount con Workload Identity
apiVersion: v1
kind: Pod
metadata:
  name: gcp-workload-identity-demo
  namespace: default
spec:
  serviceAccountName: gcp-workload-identity-sa
  containers:
    - name: app
      image: google/cloud-sdk:slim
      command: ["sleep", "infinity"]
      # El SDK de Google Cloud detectara automaticamente
      # las credenciales via Workload Identity
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
        requests:
          memory: "128Mi"
          cpu: "100m"
