apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx
    environment: lab
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
