apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sa
spec:
  serviceAccountName: app-service-account
  containers:
    - name: app
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
