# ServiceAccount para leer secrets (Ejercicio Adicional 1)
# Este archivo es para el ejercicio adicional de crear un ServiceAccount
# que pueda leer secrets en el namespace

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: secret-reader-sa
    namespace: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
